repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language_version: python3
        args: [--max-line-length=88]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: coverage\.svg
      - id: check-added-large-files
        args: ["--maxkb=1500"]

  - repo: local
    hooks:
      - id: pytest-with-coverage
        name: Run Pytest with Coverage
        entry: pytest --cov=materia_epd --cov-report=term --cov-report=xml
        language: system
        pass_filenames: false
        always_run: true

      - id: coverage-badge
        name: Generate coverage badge
        entry: genbadge coverage -i coverage.xml -o coverage.svg
        language: python
        additional_dependencies: [genbadge, defusedxml]
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: build-package
        name: Build Package
        entry: python -m build
        language: python
        additional_dependencies: [build]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/fpgmaas/deptry
    rev: 0.12.0
    hooks:
      - id: deptry
